version: '3.1'

services:
  stats-server:
    build: ./statistics/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  main-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/maindb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  main-db:
    image: postgres:13.7-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=maindb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test