version: '3.1'

services:
  stats-server:
    build: ./statistics/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stats-db:
    image: postgres:15.3-alpine3.18
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-db:
    image: postgres:15.3-alpine3.18
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=maindb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test